[package]
name = "solana-collider"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18"
thiserror = "1.0"
spl-token = { version = "4.0", features = ["no-entrypoint"] }
borsh = "0.10"

[dev-dependencies]
solana-program-test = "1.18"
solana-sdk = "1.18"
tokio = { version = "1.28", features = ["full"] }